package model;

public enum LogStatus { BOOK_EVENT_SUCCESS,
    BOOK_EVENT_USER_NOT_CONSUMER,
    BOOK_EVENT_NOT_A_TICKETED_EVENT,
    BOOK_EVENT_EVENT_NOT_ACTIVE,
    BOOK_EVENT_ALREADY_OVER,
    BOOK_EVENT_INVALID_NUM_TICKETS,
    BOOK_EVENT_NOT_ENOUGH_TICKETS_LEFT,
    BOOK_EVENT_PAYMENT_FAILED,
    BOOK_EVENT_EVENT_NOT_FOUND,
    BOOK_EVENT_PERFORMANCE_NOT_FOUND
}
